version: "3.3"
services:
  db:
    image: postgres:latest
    container_name: vprompt-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  api:
    container_name: vprompt-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
