version: "3.3"
services:
  db:
    image: postgres:latest
    container_name: vprompt-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  # api:
  #   container_name: vprompt-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./api:/app
  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis_data:/data
    restart: always
  nocodb:
    image: "nocodb/nocodb:latest"
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - "./nc_data:/usr/app/data"
