version: "3.3"
services:
  db:
    image: postgres:latest
    container_name: vprompt-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data